import type { Article, Unit } from '~/types'
import rawArticles from './constitution.json'
import { TOPICS } from './topics'

/**
 * Turns the parsed Constitution into the units the app actually drills.
 *
 * The one interesting job here is splitting: a handful of sections run to 400
 * words, and nobody memorises 400 words as a single item. A section is cut at
 * its own numbered subparagraphs first — those are the author's own seams —
 * and only then by sentence, never mid-sentence.
 *
 * Text source: lawphil.net (Arellano Law Foundation), regenerated by
 * `tools/parse-lawphil.py`. See SOURCE below.
 */

export const SOURCE = {
  name: 'The LawPhil Project — Arellano Law Foundation',
  url: 'https://lawphil.net/consti/cons1987.html',
  licence: 'CC BY-NC 4.0',
}

interface RawSection {
  n: string
  subhead: string
  text: string
}
interface RawArticle {
  numeral: string
  title: string
  sections: RawSection[]
}

/** Longest passage we will ask anyone to hold in mind at once. */
const MAX_WORDS = 85
/** Sections shorter than this are left whole even if slightly over MAX_WORDS. */
const SPLIT_ABOVE = 115

const ROMAN: Record<string, number> = {
  I: 1, II: 2, III: 3, IV: 4, V: 5, VI: 6, VII: 7, VIII: 8, IX: 9,
  X: 10, XI: 11, XII: 12, XIII: 13, XIV: 14, XV: 15, XVI: 16, XVII: 17, XVIII: 18,
}

const countWords = (s: string) => (s.match(/\S+/g) ?? []).length

/* -------------------------------------------------------------------------- */
/* Splitting                                                                   */
/* -------------------------------------------------------------------------- */

/** A slice of a section, before it is dressed up as a Unit. */
interface Piece {
  /** "(1)" when the slice is one of the section's own subparagraphs. */
  para: string
  /** 1-based when the slice was further cut by length; 0 when it wasn't. */
  part: number
  partOf: number
  text: string
}

const ABBREVIATIONS = new Set([
  'no.', 'nos.', 'sec.', 'secs.', 'art.', 'arts.', 'rep.', 'pres.',
  'gen.', 'mr.', 'mrs.', 'st.', 'jr.', 'sr.', 'p.d.', 'b.p.', 'e.o.', 'r.a.',
])

/** Split on sentence ends, tolerating the abbreviations the text actually uses. */
function toSentences(text: string): string[] {
  const words = text.split(/\s+/).filter(Boolean)
  const out: string[] = []
  let current: string[] = []

  words.forEach((word, i) => {
    current.push(word)
    const next = words[i + 1]
    if (!next) return
    if (!/[.?!][")\]]?$/.test(word)) return
    if (ABBREVIATIONS.has(word.toLowerCase())) return
    if (word.length <= 2) return // initials such as "P." in "P. D."
    if (!/^[("A-Z]/.test(next)) return // a real sentence starts big

    out.push(current.join(' '))
    current = []
  })

  if (current.length) out.push(current.join(' '))
  return out
}

/** Cut a passage into runs of whole sentences, each at most MAX_WORDS-ish. */
function cutByLength(text: string): string[] {
  const sentences = toSentences(text)
  if (sentences.length < 2) return [text]

  const total = countWords(text)
  const pieces = Math.ceil(total / MAX_WORDS)
  const target = Math.ceil(total / pieces)

  const out: string[] = []
  let current: string[] = []
  let running = 0

  for (const sentence of sentences) {
    const words = countWords(sentence)
    if (running && running + words > target * 1.3) {
      out.push(current.join(' '))
      current = []
      running = 0
    }
    current.push(sentence)
    running += words
  }
  if (current.length) out.push(current.join(' '))
  return out
}

/**
 * Find the section's own "(1) … (2) …" seams. Only an unbroken run starting at
 * (1) counts, so a stray "(1)" quoted inside a sentence can't fool us.
 */
function cutByParagraph(text: string): { para: string; text: string }[] | null {
  const marker = /\((\d{1,2})\)\s+/g
  const run: { at: number; after: number; n: number }[] = []
  let expected = 1
  let match: RegExpExecArray | null

  while ((match = marker.exec(text))) {
    if (Number(match[1]) !== expected) continue
    run.push({ at: match.index, after: match.index + match[0].length, n: expected })
    expected++
  }
  if (run.length < 2) return null

  const out: { para: string; text: string }[] = []
  const preamble = text.slice(0, run[0]!.at).trim()
  if (countWords(preamble) > 4) out.push({ para: '', text: preamble })

  run.forEach((hit, i) => {
    const end = run[i + 1]?.at ?? text.length
    out.push({ para: `(${hit.n})`, text: text.slice(hit.after, end).trim() })
  })
  return out
}

function splitSection(text: string): Piece[] {
  const whole = (para: string, body: string): Piece[] => {
    const cuts = cutByLength(body)
    return cuts.map((t, i) => ({
      para,
      part: cuts.length > 1 ? i + 1 : 0,
      partOf: cuts.length,
      text: t,
    }))
  }

  if (countWords(text) <= SPLIT_ABOVE) return [{ para: '', part: 0, partOf: 1, text }]

  const paragraphs = cutByParagraph(text)
  if (paragraphs) {
    return paragraphs.flatMap(p =>
      countWords(p.text) <= SPLIT_ABOVE
        ? [{ para: p.para, part: 0, partOf: 1, text: p.text }]
        : whole(p.para, p.text),
    )
  }
  return whole('', text)
}

/* -------------------------------------------------------------------------- */
/* Building                                                                    */
/* -------------------------------------------------------------------------- */

function articleId(numeral: string, title: string): string {
  if (!numeral) return title.toLowerCase().replace(/[^a-z]+/g, '-')
  const [main, suffix] = numeral.split('-')
  return `art-${ROMAN[main!] ?? main!.toLowerCase()}${suffix ? `-${suffix.toLowerCase()}` : ''}`
}

function buildArticle(raw: RawArticle): Article {
  const id = articleId(raw.numeral, raw.title)
  const title = raw.numeral ? `Article ${raw.numeral}` : raw.title
  const subject = raw.numeral ? raw.title : ''

  const units: Unit[] = []

  for (const section of raw.sections) {
    const pieces = splitSection(section.text)
    const topic = TOPICS[`${id}:${section.n}`] ?? ''

    pieces.forEach((piece, index) => {
      const base = section.n ? `Section ${section.n}` : raw.title
      const paraBit = piece.para ? ` ${piece.para}` : ''
      const partBit = piece.part ? ` · part ${piece.part} of ${piece.partOf}` : ''

      const shortBase = section.n ? `§${section.n}` : '¶'
      const shortPara = piece.para ? piece.para : ''
      const shortPart = piece.part ? `·${piece.part}` : ''

      units.push({
        id: `${id}.${section.n || 'body'}${pieces.length > 1 ? `.${index + 1}` : ''}`,
        articleId: id,
        articleTitle: title,
        articleSubject: subject,
        numeral: raw.numeral,
        label: `${base}${paraBit}${partBit}`,
        short: `${shortBase}${shortPara}${shortPart}`,
        cite: section.n ? `${title}, Section ${section.n}${paraBit}` : title,
        subhead: section.subhead,
        topic,
        text: piece.text,
        wordCount: countWords(piece.text),
      })
    })
  }

  return {
    id,
    numeral: raw.numeral,
    title,
    subject,
    units,
    wordCount: units.reduce((sum, u) => sum + u.wordCount, 0),
  }
}

export const ARTICLES: Article[] = (rawArticles as RawArticle[]).map(buildArticle)

export const UNITS: Unit[] = ARTICLES.flatMap(a => a.units)

const UNITS_BY_ID = new Map(UNITS.map(u => [u.id, u]))
const ARTICLES_BY_ID = new Map(ARTICLES.map(a => [a.id, a]))

export const unitById = (id: string): Unit | undefined => UNITS_BY_ID.get(id)
export const articleById = (id: string): Article | undefined => ARTICLES_BY_ID.get(id)

export const TOTAL_UNITS = UNITS.length
export const TOTAL_WORDS = UNITS.reduce((sum, u) => sum + u.wordCount, 0)
